<FirstScreen>:
    GridLayout:
        cols: 1
        padding: 10
        spacing: 10
        Image:
            id: img
            size_hint_y: 0.9
            source:
        TextInput:
            size_hint_y: 0.05
            id: user_query
        Button:
            size_hint_y: 0.05
            text: 'Search Image'
            on_press: root.set_image()


<RootWidget>:
    FirstScreen:
        id: first_screen
        name: 'first_screen'